### ISSUE TITLE
Versions 1.0.3+ not working

### ISSUE THREAD

**Issue by jamiehiggins** [innfinity-am/PermissionsFlow#3]
I'm playing around with the library and it works ok for 1.0.2 but when I try the latest 1.0.7 release or any release greater than 1.0.2 it's not working. It looks like there are no class files in the aar that is downloaded so I think their is some kind of packaging error.

Thanks for providing the library.

**Comment by robertlevonyan** [comment]
please try the latest version 1.1.1
